[tool.poetry]
name = "arena-rosnav"
version = "0.1.0"
description = ""
authors = ["ReykCS <reyk-carstens@web.de>"]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
torch = "^1.11.0"
rospkg = "^1.4.0"
PyYAML = "^6.0"
filelock = "^3.7.1"
scipy = "^1.8.1"
PyQt5 = "^5.15.7"
empy = "^3.3.4"
defusedxml = "^0.7.1"
lxml = "^4.9.1"
wandb = "^0.13.9"
seaborn = "^0.12.2"
netifaces = "^0.11.0"
torchdiffeq = "^0.2.3"
tensorboard = "^2.12.0"
diffcp = "^1.0.21"
cvxpy = "^1.3.0"
cvxpylayers = "^0.1.5"
mpi4py = "^3.1.4"
gputil = "^1.4.0"
tensorboardx = "^2.6"
gym = "^0.26.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
