goal_reached:
  reward: 15

factored_safe_distance:
  factor: -0.2

collision:
  reward: -15

approach_goal:
  pos_factor: 0.2
  neg_factor: 0.3
  _goal_update_threshold: 2.5
  _on_safe_dist_violation: true

factored_reverse_drive:
  factor: 0.05
  threshold: 0.0
  _on_safe_dist_violation: true

# approach_globalplan:
#   pos_factor: 0.05
#   neg_factor: 0.05
#   _on_safe_dist_violation: true

two_factor_velocity_difference:
  alpha: 0.01
  beta: 0.0
  _on_safe_dist_violation: true

# active_heading_direction:
#   r_angle: 0.7
#   iters: 60
#   _on_safe_dist_violation: true

ped_type_collision:
  type_reward_pairs:
    0: -2.5
    1: -5

ped_type_factored_safety_distance:
  type_factor_pairs:
    0: -0.1
    1: -0.2
  safety_distance: 1.2

max_steps_exceeded:
  reward: -15

angular_vel_constraint:
  penalty_factor: -0.05
  threshold: 0.5