goal_reached:
  reward: 15

safe_distance:
  reward: -0.25

collision:
  reward: -20

approach_goal:
  pos_factor: 0.5
  neg_factor: 0.8
  _on_safe_dist_violation: true

reverse_drive:
  reward: -0.1
  threshold: -0.5
  _on_safe_dist_violation: true

max_steps_exceeded:
  reward: -10