contestants:
  - name: teb-polite
    local_planner: teb
    inter_planner: polite

  - name: teb-aggressive
    local_planner: teb
    inter_planner: aggressive
    
  - name: cohan-polite
    local_planner: cohan
    inter_planner: polite

  - name: cohan-aggressive
    local_planner: cohan
    inter_planner: aggressive

  - name: teb-basic
    local_planner: teb
    inter_planner: bypass

  - name: dwa-basic
    local_planner: dwa
    inter_planner: bypass

  - name: applr-basic
    local_planner: applr
    inter_planner: bypass

  - name: lflh-basic
    local_planner: lflh
    inter_planner: bypass

  - name: trail-basic
    local_planner: trail
    inter_planner: bypass

  - name: cohan-basic
    local_planner: cohan
    inter_planner: bypass