contestants:
  - name: teb-polite
    local_planner: teb
    inter_planner: polite

  - name: teb-aggressive
    local_planner: teb
    inter_planner: aggressive

  - name: teb-sideways
    local_planner: teb
    inter_planner: sideways

  - name: dwa-polite
    local_planner: dwa
    inter_planner: polite

  - name: dwa-aggressive
    local_planner: dwa
    inter_planner: aggressive

  - name: dwa-sideways
    local_planner: dwa
    inter_planner: sideways

  - name: mpc-polite
    local_planner: mpc
    inter_planner: polite

  - name: mpc-aggressive
    local_planner: mpc
    inter_planner: aggressive

  - name: mpc-sideways
    local_planner: mpc
    inter_planner: sideways