DYNAMICMAP:
  algorithm: airchitect
  config: '{"prompt":5}'
  episodes: 1
  timeout: 60
PARAMETRIZED:
  file: default.xml
RANDOM:
  dynamic:
    max: 8
    min: 5
    models:
    - actor1
  interactive:
    max: 0
    min: 0
    models:
    - shelf
  seed: 1944895261
  static:
    max: 0
    min: 0
    models:
    - shelf
SCENARIO:
  file: default.json
STAGED:
  curriculum: default.yaml
  index: 0
ZONES:
  file: zones.yaml
  scenario: default.yaml
episodes: -1
